-- 1K Beats Orçamentos v6: isolamento multiempresa, RLS e links públicos imprevisíveis.
-- Execute depois de revogar a antiga chave service_role exposta no frontend.

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  plan text not null default 'basic' check (plan in ('basic', 'professional')),
  status text not null default 'active' check (status in ('active', 'suspended', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  nome text not null,
  cnpj text,
  tel text,
  email text,
  endereco text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catalogo (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  nome text not null,
  valor numeric(14,2) not null default 0 check (valor >= 0),
  categoria text not null default 'Outros',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.config (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.organizations(id) on delete cascade,
  nome text not null default '',
  cnpj text,
  tel text,
  email text,
  endereco text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orcamentos (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  numero bigint generated by default as identity,
  cliente_nome text,
  cnpj_cli text,
  referencia text,
  valido_ate date,
  desconto_tipo text default 'pct' check (desconto_tipo in ('pct', 'val')),
  desconto_valor numeric(14,2) not null default 0 check (desconto_valor >= 0),
  itens jsonb not null default '[]'::jsonb,
  observacoes text,
  empresa text,
  cnpj_emp text,
  tel_emp text,
  email_emp text,
  solicitante text,
  total numeric(14,2) not null default 0 check (total >= 0),
  status text not null default 'pendente' check (status in ('pendente', 'aprovado', 'recusado', 'cancelado')),
  public_token uuid not null default gen_random_uuid(),
  public_enabled boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Atualização segura para as tabelas da versão anterior.
alter table public.clientes add column if not exists organization_id uuid references public.organizations(id) on delete cascade;
alter table public.clientes add column if not exists updated_at timestamptz not null default now();
alter table public.catalogo add column if not exists organization_id uuid references public.organizations(id) on delete cascade;
alter table public.catalogo add column if not exists updated_at timestamptz not null default now();
alter table public.config add column if not exists organization_id uuid references public.organizations(id) on delete cascade;
alter table public.config add column if not exists updated_at timestamptz not null default now();
alter table public.orcamentos add column if not exists organization_id uuid references public.organizations(id) on delete cascade;
alter table public.orcamentos add column if not exists public_token uuid default gen_random_uuid();
alter table public.orcamentos add column if not exists public_enabled boolean not null default true;
alter table public.orcamentos add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.orcamentos add column if not exists updated_at timestamptz not null default now();

update public.orcamentos set public_token = gen_random_uuid() where public_token is null;
alter table public.orcamentos alter column public_token set default gen_random_uuid();
alter table public.orcamentos alter column public_token set not null;

create unique index if not exists orcamentos_public_token_idx on public.orcamentos(public_token);
create index if not exists organization_members_user_idx on public.organization_members(user_id);
create index if not exists clientes_org_idx on public.clientes(organization_id);
create index if not exists catalogo_org_idx on public.catalogo(organization_id);
create index if not exists orcamentos_org_created_idx on public.orcamentos(organization_id, created_at desc);
create unique index if not exists config_org_unique_idx on public.config(organization_id) where organization_id is not null;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists organizations_touch_updated_at on public.organizations;
create trigger organizations_touch_updated_at before update on public.organizations
for each row execute function public.touch_updated_at();
drop trigger if exists clientes_touch_updated_at on public.clientes;
create trigger clientes_touch_updated_at before update on public.clientes
for each row execute function public.touch_updated_at();
drop trigger if exists catalogo_touch_updated_at on public.catalogo;
create trigger catalogo_touch_updated_at before update on public.catalogo
for each row execute function public.touch_updated_at();
drop trigger if exists config_touch_updated_at on public.config;
create trigger config_touch_updated_at before update on public.config
for each row execute function public.touch_updated_at();
drop trigger if exists orcamentos_touch_updated_at on public.orcamentos;
create trigger orcamentos_touch_updated_at before update on public.orcamentos
for each row execute function public.touch_updated_at();

create or replace function public.is_org_member(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.organization_members membership
    where membership.organization_id = p_organization_id
      and membership.user_id = auth.uid()
  );
$$;

create or replace function public.is_org_admin(p_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.organization_members membership
    where membership.organization_id = p_organization_id
      and membership.user_id = auth.uid()
      and membership.role in ('owner', 'admin')
  );
$$;

revoke all on function public.is_org_member(uuid) from public;
revoke all on function public.is_org_admin(uuid) from public;
grant execute on function public.is_org_member(uuid) to authenticated;
grant execute on function public.is_org_admin(uuid) to authenticated;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.clientes enable row level security;
alter table public.catalogo enable row level security;
alter table public.config enable row level security;
alter table public.orcamentos enable row level security;
-- Remove políticas antigas permissivas antes de instalar as regras multiempresa.
do $$
declare policy_row record;
begin
  for policy_row in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('organizations', 'organization_members', 'clientes', 'catalogo', 'config', 'orcamentos')
  loop
    execute format('drop policy if exists %I on %I.%I', policy_row.policyname, policy_row.schemaname, policy_row.tablename);
  end loop;
end;
$$;

drop policy if exists organizations_select_member on public.organizations;
create policy organizations_select_member on public.organizations
for select to authenticated using (public.is_org_member(id));
drop policy if exists organizations_update_admin on public.organizations;
create policy organizations_update_admin on public.organizations
for update to authenticated using (public.is_org_admin(id)) with check (public.is_org_admin(id));

drop policy if exists members_select_same_org on public.organization_members;
create policy members_select_same_org on public.organization_members
for select to authenticated
using (user_id = auth.uid() or public.is_org_admin(organization_id));

drop policy if exists clientes_select_member on public.clientes;
create policy clientes_select_member on public.clientes
for select to authenticated using (public.is_org_member(organization_id));
drop policy if exists clientes_insert_member on public.clientes;
create policy clientes_insert_member on public.clientes
for insert to authenticated with check (public.is_org_member(organization_id));
drop policy if exists clientes_update_member on public.clientes;
create policy clientes_update_member on public.clientes
for update to authenticated using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
drop policy if exists clientes_delete_member on public.clientes;
create policy clientes_delete_member on public.clientes
for delete to authenticated using (public.is_org_member(organization_id));

drop policy if exists catalogo_select_member on public.catalogo;
create policy catalogo_select_member on public.catalogo
for select to authenticated using (public.is_org_member(organization_id));
drop policy if exists catalogo_insert_member on public.catalogo;
create policy catalogo_insert_member on public.catalogo
for insert to authenticated with check (public.is_org_member(organization_id));
drop policy if exists catalogo_update_member on public.catalogo;
create policy catalogo_update_member on public.catalogo
for update to authenticated using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
drop policy if exists catalogo_delete_member on public.catalogo;
create policy catalogo_delete_member on public.catalogo
for delete to authenticated using (public.is_org_member(organization_id));

drop policy if exists config_select_member on public.config;
create policy config_select_member on public.config
for select to authenticated using (public.is_org_member(organization_id));
drop policy if exists config_insert_admin on public.config;
create policy config_insert_admin on public.config
for insert to authenticated with check (public.is_org_admin(organization_id));
drop policy if exists config_update_admin on public.config;
create policy config_update_admin on public.config
for update to authenticated using (public.is_org_admin(organization_id)) with check (public.is_org_admin(organization_id));

drop policy if exists orcamentos_select_member on public.orcamentos;
create policy orcamentos_select_member on public.orcamentos
for select to authenticated using (public.is_org_member(organization_id));
drop policy if exists orcamentos_insert_member on public.orcamentos;
create policy orcamentos_insert_member on public.orcamentos
for insert to authenticated with check (public.is_org_member(organization_id));
drop policy if exists orcamentos_update_member on public.orcamentos;
create policy orcamentos_update_member on public.orcamentos
for update to authenticated using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
drop policy if exists orcamentos_delete_admin on public.orcamentos;
create policy orcamentos_delete_admin on public.orcamentos
for delete to authenticated using (public.is_org_admin(organization_id));

grant select, insert, update, delete on public.clientes, public.catalogo, public.orcamentos to authenticated;
grant select, insert, update on public.config to authenticated;
grant select, update on public.organizations to authenticated;
grant select on public.organization_members to authenticated;
revoke all on public.organizations, public.organization_members, public.clientes, public.catalogo, public.config, public.orcamentos from anon;

create or replace function public.bootstrap_organization(p_name text default '1000 Beats')
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_org_id uuid;
  v_had_organizations boolean;
  v_name text := left(coalesce(nullif(trim(p_name), ''), 'Minha empresa'), 120);
begin
  if v_user_id is null then
    raise exception 'authentication required';
  end if;

  select organization_id into v_org_id
  from public.organization_members
  where user_id = v_user_id
  limit 1;
  if v_org_id is not null then return v_org_id; end if;

  select exists(select 1 from public.organizations) into v_had_organizations;
  insert into public.organizations(name, slug, plan)
  values (v_name, lower(regexp_replace(v_name, '[^a-zA-Z0-9]+', '-', 'g')) || '-' || left(replace(gen_random_uuid()::text, '-', ''), 6), 'professional')
  returning id into v_org_id;

  insert into public.organization_members(organization_id, user_id, role)
  values (v_org_id, v_user_id, 'owner');

  -- Somente a primeira organização criada assume os dados legados.
  if not v_had_organizations then
    update public.clientes set organization_id = v_org_id where organization_id is null;
    update public.catalogo set organization_id = v_org_id where organization_id is null;
    update public.config set organization_id = v_org_id where organization_id is null;
    update public.orcamentos
      set organization_id = v_org_id,
          created_by = coalesce(created_by, v_user_id)
      where organization_id is null;
  end if;

  if not exists (select 1 from public.config where organization_id = v_org_id) then
    insert into public.config(organization_id, nome) values (v_org_id, v_name);
  end if;
  return v_org_id;
end;
$$;

revoke all on function public.bootstrap_organization(text) from public;
grant execute on function public.bootstrap_organization(text) to authenticated;

create or replace function public.get_public_quote(p_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'numero', quote.numero,
    'cliente_nome', quote.cliente_nome,
    'cnpj_cli', quote.cnpj_cli,
    'referencia', quote.referencia,
    'valido_ate', quote.valido_ate,
    'desconto_tipo', quote.desconto_tipo,
    'desconto_valor', quote.desconto_valor,
    'itens', quote.itens,
    'observacoes', quote.observacoes,
    'empresa', quote.empresa,
    'cnpj_emp', quote.cnpj_emp,
    'tel_emp', quote.tel_emp,
    'email_emp', quote.email_emp,
    'solicitante', quote.solicitante,
    'total', quote.total,
    'status', quote.status,
    'created_at', quote.created_at
  )
  from public.orcamentos quote
  where quote.public_token = p_token
    and quote.public_enabled = true
  limit 1;
$$;

revoke all on function public.get_public_quote(uuid) from public;
grant execute on function public.get_public_quote(uuid) to anon, authenticated;
